### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by WojciechKarpiel** [HoTT/HoTT-Agda#28]
Hello!
(disclamer: I'm new to both HoTT and Agda)

I use current (git) version of Agda (Agda version 2.6.0-dc58db0) and HoTT (commit 831dcfcc9df75f9f1c36ec1a730f82c25709f87a), both pulled 1st July

When I try to compile the library itself it gives warning:

```
/home/wojciech/Kod/HoTT-Agda/core/lib/Base.agda:70,1-25
Builtin REFL does no longer exist. It is now bound by BUILTIN
EQUALITY
when checking the pragma BUILTIN REFL idp
```

It's following piece of code:

```
infix 30 _==_
data _==_ {i} {A : Type i} (a : A) : A → Type i where
  idp : a == a

Path = _==_

{-# BUILTIN EQUALITY _==_ #-}
{-# BUILTIN REFL idp #-}
```

Simply commenting out the `BUILTIN REFL` line fixes the problem.

Last changes to these lines are from 2013. Has anyone had similar issue and knows how to fix it?

**Comment by favonia** [comment]
@WojciechKarpiel Hello! Thanks for reporting the issue. I was aware of this issue, but the next (stable) version of Agda has not been released yet. :-( Due to this I am a little bit reluctant to remove it even though I am also using the unstable (git) version. You can track issue #27 for future updates on this library, or downgrade your Agda back to 2.5.2 for the moment. Does that sound reasonable to you?

**Comment by favonia** [comment]
By the way, technically speaking this is a warning not an error, and your development should still work.

**Comment by WojciechKarpiel** [comment]
> Does that sound reasonable to you?

Sure, thanks for clarification!

**Comment by favonia** [comment]
@WojciechKarpiel Thanks. However, let me close this because it is already on the to-do list #27.
